//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sherkaty.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class s1 : DbContext
    {
        public s1()
            : base("name=s1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_coll> tbl_coll { get; set; }
        public virtual DbSet<tbl_serivice_fea> tbl_serivice_fea { get; set; }
        public virtual DbSet<tbl_service_second> tbl_service_second { get; set; }
        public virtual DbSet<tbl_service> tbl_service { get; set; }
        public virtual DbSet<tbl_service_card> tbl_service_card { get; set; }
        public virtual DbSet<tbl_blog> tbl_blog { get; set; }
    }
}
