//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sherkaty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_service_card
    {
        public int scid { get; set; }
        public string f1title { get; set; }
        public string f1text { get; set; }
        public string f1check { get; set; }
        public string f2title { get; set; }
        public string f2text { get; set; }
        public string f2check { get; set; }
        public string f3titlle { get; set; }
        public string f3text { get; set; }
        public string f3check { get; set; }
        public string ctitle { get; set; }
        public string cdes { get; set; }
    }
}
