//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sherkaty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_service
    {
        public int sid { get; set; }
        public string smtitle { get; set; }
        public string headimg { get; set; }
        public string des { get; set; }
        public string vid { get; set; }
        public string check1 { get; set; }
        public string check2 { get; set; }
        public string check3 { get; set; }
        public string check4 { get; set; }
    }
}
