//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sherkaty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_service_second
    {
        public int srcid { get; set; }
        public string srcdes { get; set; }
        public string c1title { get; set; }
        public string c1img { get; set; }
        public string c2title { get; set; }
        public string c2img { get; set; }
        public string c3title { get; set; }
        public string c3img { get; set; }
        public string secondTitle { get; set; }
        public string secondDes { get; set; }
    }
}
