//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sherkaty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_serivice_fea
    {
        public int ssid { get; set; }
        public string thtitle { get; set; }
        public string thdes { get; set; }
        public string ch1 { get; set; }
        public string ch2 { get; set; }
        public string ch3 { get; set; }
        public string ch4 { get; set; }
        public string ch5 { get; set; }
        public string ch6 { get; set; }
    }
}
