//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sherkaty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_coll
    {
        public int coid { get; set; }
        public string coname { get; set; }
        public string cofamily { get; set; }
        public string coposition { get; set; }
        public string coemail { get; set; }
        public string coexperience { get; set; }
        public Nullable<int> cophnumber { get; set; }
        public string colocation { get; set; }
        public string coinfo { get; set; }
        public string coexpertise { get; set; }
        public string coabout { get; set; }
        public string coimgpth { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
    }
}
