//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sherkaty.Models
{
    using System;
    using System.Collections.Generic;
  
    public partial class tbl_blog
    {
        public int bid { get; set; }
        public string btitle { get; set; }
        public string img { get; set; }
        public string firsttext { get; set; }
        public string bold { get; set; }
        public string sectext { get; set; }
        public string sectitle { get; set; }
        public string thtext { get; set; }
        public string c1 { get; set; }
        public string c2 { get; set; }
        public string c3 { get; set; }
        public string c4 { get; set; }
        public string c5 { get; set; }
        public string ltext { get; set; }
        public int dateday { get; set; }
        public string datemon { get; set; }
        public int dateye { get; set; }
    }
}
